### ISSUE TITLE
Installation docu mentions Youtube

### ISSUE THREAD

**Issue by kevinpapst** [Korbak/freshrss-Hooktube#1]
You missed one line in your repo, check the REAMDE file (installation section) where you mention "freshrss-Hooktube-master/xExtension-YouTube".

See https://github.com/Korbak/freshrss-Hooktube/blame/147738bb95fccd90c96773e6cdbbba15dbe2d815/README.md#L16

**Comment by Korbak** [comment]
Corrected ! I should have s/ it ;). Thanks !
